config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#index'  
  get 'homes/index'

  devise_for :users
  scope '/admin' do
    resources :users
  end

  resources :articles
  resources :roles
  resources :users

  authenticated :user do
    root to: 'articles#index', as: :authenticated_root
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # Guest user

    if user.id.present?
      if user.admin?
        can :read, User
        can :create, User
        can :update, User
        can :read, Article
      elsif user.editor?
        can :read, Article
        can :create, Article
        can :update, Article do |article|
          article.try(:user) == user
        end
        can :destroy, Article do |article|
          article.try(:user) == user
        end
      elsif user.vanila_user?
        can :read, Article
      end
    else
      can :index, Article
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates_presence_of :title, :category
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :role, optional: true
  has_many :articles, dependent: :destroy
  validates :name, presence: true
  before_save :assign_role

  def assign_role
    self.role = Role.find_by name: 'User' if role.nil?
  end

  def admin?
    role.name == 'Admin'
  end

  def editor?
    role.name == 'Editor'
  end

  def vanila_user?
    role.name == 'User'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do
    flash[:error] = 'Access denied!'
    redirect_to root_url
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: :index
  load_and_authorize_resource
  # before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  def index
    @articles = Article.all
  end

  # GET /articles/1
  def show; end

  # GET /articles/new
  def new
    # @article = Article.new
  end

  # GET /articles/1/edit
  def edit; end

  # POST /articles
  def create
    # @article = Article.new(article_params)
    @article.user_id = current_user.id

    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /articles/1
  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  # def set_article
  #   @article = Article.find(params[:id])
  # end

  # Only allow a trusted parameter "white list" through.
  def article_params
    params.require(:article).permit(:title, :content, :category, :user_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @articles = Article.all.group_by(&:category)
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  # before_action :set_role, only: [:show, :edit, :update, :destroy]

  def index
    @roles = Role.all
  end

  def show; end

  def new
    # @role = Role.new
  end

  def edit; end

  # POST /roles
  def create
    if @role.save
      redirect_to @role, notice: 'Role was successfully created.'
    else
      render :new
    end
  end

  def update
    if @role.update(role_params)
      redirect_to @role, notice: 'Role was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @role.destroy
    redirect_to roles_url, notice: 'Role was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  # def set_role
  #   @role = Role.find(params[:id])
  # end

  # Only allow a trusted parameter "white list" through.
  def role_params
    params.require(:role).permit(:name, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  # before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show; end

  def new
    # @user = User.new
  end

  def edit; end

  def create
    # @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def update
    if user_params[:password].blank?
      user_params.delete(:password)
      user_params.delete(:password_confirmation)
    end

    if successfully_updated?(@user)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

  def successfully_updated?(user)
    if needs_password?(user, user_params)
      @user.update(user_params)
    else
      @user.update_without_password(user_params)
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  # def set_user
  #   @user = User.find(params[:id])
  # end

  # Only allow a trusted parameter "white list" through.
  def user_params
    params.require(:user).permit(:name, :role_id, :email, :password, :password_confirmation)
  end

  def needs_password?(_user, params)
    params[:password].present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def select_category
    [
      ['Category A', 'Category A'],
      ['Category B', 'Category B'],
      ['Category C', 'Category C']
    ]
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.select :category, options_for_select(select_category), {:prompt => 'Select Category'} %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Category</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.content %></td>
        <td><%= article.category %></td>
        <td><%= article.user.name %></td>
        <td><%= link_to 'Show', article %></td>
        <td>
          <% if can? :update, article %>
            <%= link_to 'Edit', edit_article_path(article) %>
          <% end %>
        </td>
        <td>
          <% if can? :destroy, article %>
            <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :create, Article %>
  <%= link_to 'New Article', new_article_path %>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>

<p>
  <strong>Category:</strong>
  <%= @article.category %>
</p>

<p>
  <strong>User:</strong>
  <%= @article.user.name %>
</p>

<% if can? :update, @article %>
  <%= link_to 'Edit', edit_article_path(@article) %>
<% end %>
<br>
<%= link_to 'Back', articles_path %>

app/views/homes/index.html.erb
<h1>List of Article based on category</h1>

<table>
  <thead>
    <tr>
      <th>Category Name</th>
      <th>Article Title</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |category, articles| %>
      <tr>
        <td><%= category %></td>
        <td>
          <ul>
            <% articles.first(3).each do |article| %>
              <li><%= article.title %></li>
            <% end %>
        </ul>
        </td>
      </tr>
    <% end %>
  </tbody>
  
</table>

<br>

<%#= link_to 'Article List', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PujaRorCompetencyTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="flex-container">
      <header>
        <% if user_signed_in? %>
          Signed in as <%= current_user.email %>.<br>
          Not you?
          <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path %> or
          <%= link_to "sign in", new_user_session_path %>
        <% end %>

        <nav>
          <%= link_to "Home", homes_index_path %> |
          <%= link_to "Article List", articles_path %> |
          <% if current_user&.admin? %>
            <%= link_to "User List", users_path %> 
          <% end %>
        </nav>
      </header>

      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>

      <main>
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/roles/_form.html.erb
<%= form_with(model: role, local: true) do |form| %>
  <% if role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
        <% role.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<h1>Roles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.name %></td>
        <td><%= role.description %></td>
        <td><%= link_to 'Show', role %></td>
        <td><%= link_to 'Edit', edit_role_path(role) %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @role.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @role.description %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <% if controller.action_name == "new" %>
    <div class="field">
      <%= form.label :password %><br>
      <%= form.password_field :password %>
    </div>
  <% else %>
    <div class="field">
      <%= form.label :password %><br>
      <%= form.password_field :password, placeholder: "Leave blank if unchanged" %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :role_id %>
    <%= collection_select(:user, :role_id, Role.all, :id, :name, { prompt: true }) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Role</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.role.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>